using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using TOM = Microsoft.AnalysisServices.Tabular;

var outputPath = args.Length > 0
    ? Path.GetFullPath(args[0])
    : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "generated.go"));

var generator = new GoGenerator(typeof(TOM.Server).Assembly);
Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generator.Generate(), new UTF8Encoding(false));
Console.WriteLine(
    $"Generated {outputPath}: {generator.GeneratedTypeCount} types, {generator.GeneratedMemberCount} members, " +
    $"{generator.OfficialDocumentationCount} official docs, {generator.FallbackDocumentationCount} fallbacks");

internal sealed class GoGenerator
{
    private static readonly HashSet<string> GoKeywords =
    [
        "break", "default", "func", "interface", "select", "case", "defer", "go", "map",
        "struct", "chan", "else", "goto", "package", "switch", "const", "fallthrough",
        "if", "range", "type", "continue", "for", "import", "return", "var"
    ];

    private readonly Assembly _assembly;
    private readonly Type[] _types;
    private readonly Dictionary<Type, string> _goNames = [];
    private readonly StringBuilder _output = new();
    private readonly XmlDocumentation _docs;

    public GoGenerator(Assembly assembly)
    {
        _assembly = assembly;
        _types = assembly.GetExportedTypes()
            .Where(type => type.Namespace?.StartsWith("Microsoft.AnalysisServices.Tabular", StringComparison.Ordinal) == true)
            .OrderBy(type => type.FullName, StringComparer.Ordinal)
            .ToArray();
        _docs = XmlDocumentation.Load(Path.GetDirectoryName(assembly.Location)!);
        BuildTypeNames();
    }

    public int GeneratedTypeCount { get; private set; }
    public int GeneratedMemberCount { get; private set; }
    public int OfficialDocumentationCount { get; private set; }
    public int FallbackDocumentationCount { get; private set; }

    public string Generate()
    {
        Line("//go:build windows");
        Line();
        Line("// Code generated by TomGen from Microsoft.AnalysisServices; DO NOT EDIT.");
        Line();
        Line("package tom");
        Line();

        foreach (var type in _types.Where(CanGenerateType))
        {
            if (type.IsEnum)
            {
                GenerateEnum(type);
            }
            else
            {
                GenerateObject(type);
            }
            GeneratedTypeCount++;
        }

        var skipped = _types.Where(type => !CanGenerateType(type)).Select(type => type.FullName).ToArray();
        if (skipped.Length > 0)
        {
            Line("// Open generic CLR types remain available through Client.Call and Value.InvokeAny:");
            foreach (var name in skipped)
            {
                Line($"//   {name}");
            }
        }

        return _output.ToString();
    }

    private void GenerateEnum(Type type)
    {
        var goName = _goNames[type];
        Documentation(goName, type, $"Maps CLR enum {type.FullName}.");
        Line($"type {goName} string");
        Line();
        Line("const (");
        foreach (var name in Enum.GetNames(type))
        {
            var constantName = goName + Identifier(name);
            var field = type.GetField(name, BindingFlags.Static | BindingFlags.Public)!;
            Documentation(constantName, field, $"Maps {type.FullName}.{name}.", "\t");
            Line($"\t{constantName} {goName} = {Quote(name)}");
        }
        Line(")");
        Line();
    }

    private void GenerateObject(Type type)
    {
        var goName = _goNames[type];
        var clrName = FriendlyTypeName(type);
        var properties = type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(property => property.GetIndexParameters().Length == 0)
            .GroupBy(property => property.Name, StringComparer.Ordinal)
            .Select(group => group.First())
            .OrderBy(property => property.Name, StringComparer.Ordinal)
            .ToArray();
        var snapshotProperties = SnapshotProperties(properties);

        Documentation(goName, type, $"Maps CLR type {clrName}.");
        Line($"type {goName} struct {{");
        Line("\tobjectRef");
        foreach (var property in snapshotProperties)
        {
            var propertyName = Identifier(property.Name);
            Documentation(propertyName, property, $"Gets {goName}.{property.Name}.", "\t");
            Line($"\t{propertyName} {MapReturnType(property.PropertyType).GoType} " +
                 $"`json:{Quote(property.Name)}`");
        }
        Line("}");
        Line();
        Documentation($"As{goName}", null, $"Wraps a managed TOM handle as {goName}.", learnLink: LearnLink(type));
        Line($"func As{goName}(value Value) {goName} {{ return {goName}{{objectRef: objectRef{{Value: value}}}} }}");
        Line();

        if (type is { IsClass: true, IsAbstract: false })
        {
            GenerateConstructors(type, goName, clrName);
        }

        var reservedInstanceNames = type.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(method => !method.IsSpecialName)
            .Select(method => Identifier(method.Name))
            .ToHashSet(StringComparer.Ordinal);

        GenerateSnapshot(goName, snapshotProperties, reservedInstanceNames);

        foreach (var property in properties)
        {
            GenerateInstanceProperty(goName, property, reservedInstanceNames);
        }

        foreach (var field in type.GetFields(BindingFlags.Instance | BindingFlags.Public)
                     .OrderBy(field => field.Name, StringComparer.Ordinal))
        {
            GenerateInstanceField(goName, field, reservedInstanceNames);
        }

        GenerateInstanceMethods(type, goName);
        GenerateStaticProperties(type, goName, clrName);
        GenerateStaticFields(type, goName, clrName);
        GenerateStaticMethods(type, goName, clrName);
    }

    private PropertyInfo[] SnapshotProperties(PropertyInfo[] properties) =>
        properties
            .Where(property => property.CanRead &&
                               property.GetMethod is { IsStatic: false } &&
                               MapReturnType(property.PropertyType).Kind == ReturnKind.Primitive)
            .ToArray();

    private void GenerateSnapshot(string owner, PropertyInfo[] snapshotProperties, HashSet<string> reservedNames)
    {
        if (snapshotProperties.Length == 0)
        {
            return;
        }

        var methodName = reservedNames.Contains("Snapshot") ? "ReadSnapshot" : "Snapshot";
        Comment($"{methodName} returns a copy of {owner} with all scalar properties populated in one bridge call.", "");
        Line($"func (receiver {owner}) {methodName}() ({owner}, error) {{");
        Line("\tresult := receiver");
        Line($"\terr := receiver.objectRef.Value.Snapshot([]string{{" +
             string.Join(", ", snapshotProperties.Select(property => Quote(property.Name))) + "}, &result)");
        Line("\treturn result, err");
        Line("}");
        Line();
        GeneratedMemberCount++;
    }

    private void GenerateConstructors(Type type, string goName, string clrName)
    {
        var constructors = type.GetConstructors(BindingFlags.Instance | BindingFlags.Public)
            .OrderBy(constructor => constructor.GetParameters().Length)
            .ThenBy(SignatureKey, StringComparer.Ordinal)
            .ToArray();
        var names = OverloadNames("New" + goName, constructors);
        for (var index = 0; index < constructors.Length; index++)
        {
            var constructor = constructors[index];
            var parameters = constructor.GetParameters();
            var declaration = ParameterDeclaration(parameters);
            Documentation(names[index], constructor, $"Creates a new {goName}.");
            Line($"func {names[index]}(client *Client{Comma(declaration)}) ({goName}, error) {{");
            Line($"\tvalue, err := client.CreateExact({Quote(clrName)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})");
            Line($"\treturn As{goName}(value), err");
            Line("}");
            Line();
            GeneratedMemberCount++;
        }
    }

    private void GenerateInstanceProperty(string owner, PropertyInfo property, HashSet<string> reservedNames)
    {
        var propertyName = Identifier(property.Name);
        var getterName = reservedNames.Contains(propertyName) ? "Get" + propertyName : propertyName;
        if (property.CanRead &&
            property.GetMethod is { IsStatic: false } &&
            MapReturnType(property.PropertyType).Kind != ReturnKind.Primitive)
        {
            Documentation(getterName, property, $"Gets {owner}.{property.Name}.");
            GenerateReadBody($"func (receiver {owner}) {getterName}()", property.PropertyType,
                $"receiver.objectRef.Value.Get({Quote(property.Name)}, &result)",
                $"receiver.objectRef.Value.GetValue({Quote(property.Name)})",
                $"receiver.objectRef.Value.GetAny({Quote(property.Name)})");
            GeneratedMemberCount++;
            reservedNames.Add(getterName);
            GenerateCollectionItemsHelper(owner, property, getterName, reservedNames);
        }
        if (property.CanWrite && property.SetMethod is { IsStatic: false })
        {
            var parameterType = GoParameterType(property.PropertyType);
            Documentation($"Set{propertyName}", property, $"Sets {owner}.{property.Name}.");
            Line($"func (receiver {owner}) Set{propertyName}(input {parameterType}) error {{");
            Line($"\treturn receiver.objectRef.Value.Set({Quote(property.Name)}, input)");
            Line("}");
            Line();
            GeneratedMemberCount++;
        }
    }

    private void GenerateCollectionItemsHelper(
        string owner,
        PropertyInfo property,
        string getterName,
        HashSet<string> reservedNames)
    {
        var itemType = CollectionItemType(property.PropertyType);
        if (!_goNames.ContainsKey(property.PropertyType) ||
            itemType is null ||
            !_goNames.TryGetValue(itemType, out var itemName))
        {
            return;
        }

        var helperName = itemName + "Items";
        if (reservedNames.Contains(helperName))
        {
            helperName = Identifier(property.Name) + "Items";
        }
        for (var suffix = 2; !reservedNames.Add(helperName); suffix++)
        {
            helperName = Identifier(property.Name) + "Items" + suffix;
        }

        Comment($"{helperName} gets {owner}.{property.Name} and returns up to limit items.", "");
        Line($"func (receiver {owner}) {helperName}(limit int) ([]{itemName}, error) {{");
        Line($"\tcollection, err := receiver.{getterName}()");
        Line("\tif err != nil {");
        Line("\t\treturn nil, err");
        Line("\t}");
        Line("\tif collection.TOMValue().Handle == 0 {");
        Line("\t\treturn nil, nil");
        Line("\t}");
        Line("\titems, err := collection.Items(limit)");
        Line($"\tresult := make([]{itemName}, len(items))");
        Line("\tfor index := range items {");
        Line($"\t\tresult[index] = As{itemName}(items[index])");
        Line("\t}");
        Line("\treturn result, err");
        Line("}");
        Line();
        GeneratedMemberCount++;
    }

    private Type? CollectionItemType(Type type)
    {
        var enumerableItem = type.GetInterfaces()
            .Where(candidate => candidate.IsGenericType &&
                                candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            .Select(candidate => candidate.GetGenericArguments()[0])
            .FirstOrDefault();
        if (enumerableItem is not null)
        {
            return enumerableItem;
        }

        var indexerItems = type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(property => property.CanRead &&
                               property.GetIndexParameters().Length == 1 &&
                               _goNames.ContainsKey(property.PropertyType))
            .Select(property => property.PropertyType)
            .Distinct()
            .ToArray();
        return indexerItems.Length == 1 ? indexerItems[0] : null;
    }

    private void GenerateInstanceField(string owner, FieldInfo field, HashSet<string> reservedNames)
    {
        var fieldName = Identifier(field.Name);
        var getterName = reservedNames.Contains(fieldName) ? "Get" + fieldName : fieldName;
        Documentation(getterName, field, $"Gets {owner}.{field.Name}.");
        GenerateReadBody($"func (receiver {owner}) {getterName}()", field.FieldType,
            $"receiver.objectRef.Value.GetField({Quote(field.Name)}, &result)",
            $"receiver.objectRef.Value.GetFieldValue({Quote(field.Name)})",
            $"receiver.objectRef.Value.GetFieldAny({Quote(field.Name)})");
        GeneratedMemberCount++;
        if (!field.IsInitOnly && !field.IsLiteral)
        {
            Documentation($"Set{fieldName}", field, $"Sets {owner}.{field.Name}.");
            Line($"func (receiver {owner}) Set{fieldName}(input {GoParameterType(field.FieldType)}) error {{");
            Line($"\treturn receiver.objectRef.Value.SetField({Quote(field.Name)}, input)");
            Line("}");
            Line();
            GeneratedMemberCount++;
        }
    }

    private void GenerateInstanceMethods(Type type, string owner)
    {
        var groups = type.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(method => !method.IsSpecialName && method.DeclaringType != typeof(object))
            .GroupBy(method => method.Name, StringComparer.Ordinal)
            .OrderBy(group => group.Key, StringComparer.Ordinal);

        foreach (var group in groups)
        {
            var methods = group.OrderBy(method => method.GetParameters().Length)
                .ThenBy(SignatureKey, StringComparer.Ordinal)
                .ToArray();
            var names = OverloadNames(Identifier(group.Key), methods);
            for (var index = 0; index < methods.Length; index++)
            {
                GenerateInstanceMethod(owner, names[index], methods[index]);
            }
        }
    }

    private void GenerateInstanceMethod(string owner, string name, MethodInfo method)
    {
        var parameters = method.GetParameters();
        if (method.IsGenericMethodDefinition || parameters.Any(parameter => parameter.ParameterType.IsByRef))
        {
            Documentation(name, method, $"Invokes {owner}.{method.Name}.");
            Line($"func (receiver {owner}) {name}(args ...any) (any, error) {{");
            Line($"\treturn receiver.objectRef.Value.InvokeAny({Quote(method.Name)}, args...)");
            Line("}");
            Line();
            GeneratedMemberCount++;
            return;
        }

        var declaration = ParameterDeclaration(parameters);
        Documentation(name, method, $"Invokes {owner}.{method.Name}.");
        GenerateInvokeBody(
            $"func (receiver {owner}) {name}({declaration})",
            method.ReturnType,
            $"receiver.objectRef.Value.InvokeExact({Quote(method.Name)}, {TypeList(parameters)}, &result{Comma(ArgumentList(parameters))})",
            $"receiver.objectRef.Value.InvokeExactValue({Quote(method.Name)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})",
            $"receiver.objectRef.Value.InvokeExactAny({Quote(method.Name)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})",
            $"receiver.objectRef.Value.InvokeExact({Quote(method.Name)}, {TypeList(parameters)}, nil{Comma(ArgumentList(parameters))})");
        GeneratedMemberCount++;
    }

    private void GenerateStaticProperties(Type type, string owner, string clrName)
    {
        foreach (var property in type.GetProperties(BindingFlags.Static | BindingFlags.Public)
                     .Where(property => property.GetIndexParameters().Length == 0)
                     .GroupBy(property => property.Name, StringComparer.Ordinal)
                     .Select(group => group.First())
                     .OrderBy(property => property.Name, StringComparer.Ordinal))
        {
            var name = Identifier(property.Name);
            if (property.CanRead)
            {
                Documentation(owner + name, property, $"Gets static property {type.Name}.{property.Name}.");
                GenerateReadBody($"func {owner}{name}(client *Client)", property.PropertyType,
                    $"client.GetStatic({Quote(clrName)}, {Quote(property.Name)}, &result)",
                    $"client.GetStaticValue({Quote(clrName)}, {Quote(property.Name)})",
                    $"client.GetStaticAny({Quote(clrName)}, {Quote(property.Name)})");
                GeneratedMemberCount++;
            }
            if (property.CanWrite)
            {
                Documentation($"Set{owner}{name}", property, $"Sets static property {type.Name}.{property.Name}.");
                Line($"func Set{owner}{name}(client *Client, input {GoParameterType(property.PropertyType)}) error {{");
                Line($"\treturn client.SetStatic({Quote(clrName)}, {Quote(property.Name)}, input)");
                Line("}");
                Line();
                GeneratedMemberCount++;
            }
        }
    }

    private void GenerateStaticFields(Type type, string owner, string clrName)
    {
        foreach (var field in type.GetFields(BindingFlags.Static | BindingFlags.Public)
                     .OrderBy(field => field.Name, StringComparer.Ordinal))
        {
            var name = Identifier(field.Name);
            Documentation(owner + name, field, $"Gets static field {type.Name}.{field.Name}.");
            GenerateReadBody($"func {owner}{name}(client *Client)", field.FieldType,
                $"client.GetStaticField({Quote(clrName)}, {Quote(field.Name)}, &result)",
                $"client.GetStaticFieldValue({Quote(clrName)}, {Quote(field.Name)})",
                $"client.GetStaticFieldAny({Quote(clrName)}, {Quote(field.Name)})");
            GeneratedMemberCount++;
            if (!field.IsInitOnly && !field.IsLiteral)
            {
                Documentation($"Set{owner}{name}", field, $"Sets static field {type.Name}.{field.Name}.");
                Line($"func Set{owner}{name}(client *Client, input {GoParameterType(field.FieldType)}) error {{");
                Line($"\treturn client.SetStaticField({Quote(clrName)}, {Quote(field.Name)}, input)");
                Line("}");
                Line();
                GeneratedMemberCount++;
            }
        }
    }

    private void GenerateStaticMethods(Type type, string owner, string clrName)
    {
        var groups = type.GetMethods(BindingFlags.Static | BindingFlags.Public)
            .Where(method => !method.IsSpecialName)
            .GroupBy(method => method.Name, StringComparer.Ordinal)
            .OrderBy(group => group.Key, StringComparer.Ordinal);
        foreach (var group in groups)
        {
            var methods = group.OrderBy(method => method.GetParameters().Length)
                .ThenBy(SignatureKey, StringComparer.Ordinal)
                .ToArray();
            var names = OverloadNames(owner + Identifier(group.Key), methods);
            for (var index = 0; index < methods.Length; index++)
            {
                var method = methods[index];
                var parameters = method.GetParameters();
                if (method.IsGenericMethodDefinition || parameters.Any(parameter => parameter.ParameterType.IsByRef))
                {
                    Documentation(names[index], method, $"Invokes static method {type.Name}.{method.Name}.");
                    Line($"func {names[index]}(client *Client, args ...any) (any, error) {{");
                    Line($"\treturn client.InvokeStaticAny({Quote(clrName)}, {Quote(method.Name)}, args...)");
                    Line("}");
                    Line();
                    GeneratedMemberCount++;
                    continue;
                }

                Documentation(names[index], method, $"Invokes static method {type.Name}.{method.Name}.");
                GenerateInvokeBody(
                    $"func {names[index]}(client *Client{Comma(ParameterDeclaration(parameters))})",
                    method.ReturnType,
                    $"client.InvokeStaticExact({Quote(clrName)}, {Quote(method.Name)}, {TypeList(parameters)}, &result{Comma(ArgumentList(parameters))})",
                    $"client.InvokeStaticExactValue({Quote(clrName)}, {Quote(method.Name)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})",
                    $"client.InvokeStaticExactAny({Quote(clrName)}, {Quote(method.Name)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})",
                    $"client.InvokeStaticExact({Quote(clrName)}, {Quote(method.Name)}, {TypeList(parameters)}, nil{Comma(ArgumentList(parameters))})");
                GeneratedMemberCount++;
            }
        }
    }

    private void GenerateReadBody(string declaration, Type resultType, string primitiveCall, string objectCall, string anyCall)
    {
        var mapping = MapReturnType(resultType);
        Line($"{declaration} ({mapping.GoType}, error) {{");
        if (mapping.Kind == ReturnKind.Object)
        {
            Line($"\tresult, err := {objectCall}");
            Line($"\treturn As{mapping.GoType}(result), err");
        }
        else if (mapping.Kind == ReturnKind.Any)
        {
            Line($"\treturn {anyCall}");
        }
        else
        {
            Line($"\tvar result {mapping.GoType}");
            Line($"\terr := {primitiveCall}");
            Line("\treturn result, err");
        }
        Line("}");
        Line();
    }

    private void GenerateInvokeBody(
        string declaration,
        Type resultType,
        string primitiveCall,
        string objectCall,
        string anyCall,
        string voidCall)
    {
        if (resultType == typeof(void))
        {
            Line($"{declaration} error {{");
            Line($"\treturn {voidCall}");
            Line("}");
            Line();
            return;
        }

        var mapping = MapReturnType(resultType);
        Line($"{declaration} ({mapping.GoType}, error) {{");
        if (mapping.Kind == ReturnKind.Object)
        {
            Line($"\tresult, err := {objectCall}");
            Line($"\treturn As{mapping.GoType}(result), err");
        }
        else if (mapping.Kind == ReturnKind.Any)
        {
            Line($"\treturn {anyCall}");
        }
        else
        {
            Line($"\tvar result {mapping.GoType}");
            Line($"\terr := {primitiveCall}");
            Line("\treturn result, err");
        }
        Line("}");
        Line();
    }

    private ReturnMapping MapReturnType(Type type)
    {
        var nullable = Nullable.GetUnderlyingType(type);
        type = nullable ?? type;
        if (_goNames.TryGetValue(type, out var goName))
        {
            return type.IsEnum
                ? new ReturnMapping(goName, ReturnKind.Primitive)
                : new ReturnMapping(goName, ReturnKind.Object);
        }
        return type switch
        {
            _ when type == typeof(string) => new("string", ReturnKind.Primitive),
            _ when type == typeof(bool) => new("bool", ReturnKind.Primitive),
            _ when type == typeof(byte) => new("uint8", ReturnKind.Primitive),
            _ when type == typeof(sbyte) => new("int8", ReturnKind.Primitive),
            _ when type == typeof(short) => new("int16", ReturnKind.Primitive),
            _ when type == typeof(ushort) => new("uint16", ReturnKind.Primitive),
            _ when type == typeof(int) => new("int", ReturnKind.Primitive),
            _ when type == typeof(uint) => new("uint", ReturnKind.Primitive),
            _ when type == typeof(long) => new("int64", ReturnKind.Primitive),
            _ when type == typeof(ulong) => new("uint64", ReturnKind.Primitive),
            _ when type == typeof(float) => new("float32", ReturnKind.Primitive),
            _ when type == typeof(double) || type == typeof(decimal) => new("float64", ReturnKind.Primitive),
            _ when type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(TimeSpan)
                => new("string", ReturnKind.Primitive),
            _ => new("any", ReturnKind.Any)
        };
    }

    private string GoParameterType(Type type)
    {
        if (type.IsByRef) type = type.GetElementType()!;
        var nullable = Nullable.GetUnderlyingType(type);
        type = nullable ?? type;
        string result;
        if (_goNames.TryGetValue(type, out var goName))
        {
            result = goName;
        }
        else
        {
            result = MapReturnType(type).GoType;
        }
        return nullable is not null && result != "any" ? "*" + result : result;
    }

    private string ParameterDeclaration(ParameterInfo[] parameters) =>
        string.Join(", ", parameters.Select((parameter, index) =>
            $"{ParameterName(parameter, index)} {GoParameterType(parameter.ParameterType)}"));

    private string ArgumentList(ParameterInfo[] parameters) =>
        string.Join(", ", parameters.Select(ParameterName));

    private string TypeList(ParameterInfo[] parameters) =>
        "[]string{" + string.Join(", ", parameters.Select(parameter => Quote(FriendlyTypeName(parameter.ParameterType)))) + "}";

    private static string SignatureKey(MethodBase method) =>
        string.Join("|", method.GetParameters().Select(parameter => FriendlyTypeName(parameter.ParameterType)));

    private string[] OverloadNames(string baseName, MethodBase[] methods)
    {
        if (methods.Length == 1) return [baseName];
        var result = new string[methods.Length];
        var used = new HashSet<string>(StringComparer.Ordinal);
        for (var index = 0; index < methods.Length; index++)
        {
            var candidate = index == 0 ? baseName : baseName + "With" + ParameterSuffix(methods[index].GetParameters());
            if (!used.Add(candidate))
            {
                var suffix = 2;
                while (!used.Add(candidate + suffix)) suffix++;
                candidate += suffix;
            }
            result[index] = candidate;
        }
        return result;
    }

    private string ParameterSuffix(ParameterInfo[] parameters)
    {
        if (parameters.Length == 0) return "NoArguments";
        var names = parameters.Select((parameter, index) =>
        {
            var name = Identifier(parameter.Name ?? $"Argument{index + 1}");
            return name.Length > 1 ? name : TypeIdentifier(parameter.ParameterType);
        });
        return string.Concat(names);
    }

    private string TypeIdentifier(Type type)
    {
        if (type.IsByRef) type = type.GetElementType()!;
        if (type.IsArray) return TypeIdentifier(type.GetElementType()!) + "Array";
        return _goNames.TryGetValue(type, out var name) ? name : Identifier(type.Name.Split('`')[0]);
    }

    private void BuildTypeNames()
    {
        var used = new HashSet<string>(StringComparer.Ordinal)
        {
            "Client", "Value", "Instance"
        };
        foreach (var type in _types.Where(CanGenerateType))
        {
            var baseName = Identifier(type.Name.Split('`')[0].Replace('+', '_'));
            var name = baseName;
            for (var suffix = 2; !used.Add(name); suffix++)
            {
                name = baseName + suffix;
            }
            _goNames[type] = name;
        }
    }

    private static bool CanGenerateType(Type type) => !type.ContainsGenericParameters;

    private void Documentation(
        string identifier,
        MemberInfo? member,
        string fallback,
        string indent = "",
        string? learnLink = null)
    {
        var entry = member is null ? null : _docs.Find(member);
        if (entry is null)
        {
            FallbackDocumentationCount++;
        }
        else
        {
            OfficialDocumentationCount++;
        }
        var summary = entry?.Summary ?? fallback;
        Comment(summary, indent);
        if (!string.IsNullOrWhiteSpace(entry?.Remarks))
        {
            DocumentationDetail("Remarks", entry.Remarks, indent);
        }
        if (member is Type type)
        {
            foreach (var parameter in type.GetGenericArguments())
            {
                var description = entry?.TypeParameters.GetValueOrDefault(parameter.Name);
                DocumentationDetail(
                    $"Type parameter {parameter.Name}",
                    string.IsNullOrWhiteSpace(description)
                        ? $"CLR type parameter {parameter.Name}."
                        : description,
                    indent);
            }
        }
        else if (member is MethodBase method)
        {
            if (method is MethodInfo { IsGenericMethodDefinition: true } genericMethod)
            {
                foreach (var parameter in genericMethod.GetGenericArguments())
                {
                    var description = entry?.TypeParameters.GetValueOrDefault(parameter.Name);
                    DocumentationDetail(
                        $"Type parameter {parameter.Name}",
                        string.IsNullOrWhiteSpace(description)
                            ? $"CLR method type parameter {parameter.Name}."
                            : description,
                        indent);
                }
            }
            var parameters = method.GetParameters();
            for (var index = 0; index < parameters.Length; index++)
            {
                var parameter = parameters[index];
                var name = parameter.Name ?? $"argument{index + 1}";
                var description = entry?.Parameters.GetValueOrDefault(name);
                DocumentationDetail(
                    $"Parameter {ParameterName(parameter, index)}",
                    string.IsNullOrWhiteSpace(description)
                        ? $"CLR type {FriendlyTypeName(parameter.ParameterType)}."
                        : description,
                    indent);
            }
        }
        if (member is PropertyInfo property)
        {
            DocumentationDetail(
                "Value",
                string.IsNullOrWhiteSpace(entry?.Value)
                    ? $"CLR type {FriendlyTypeName(property.PropertyType)}."
                    : entry.Value,
                indent);
        }
        else if (member is FieldInfo field && !field.DeclaringType!.IsEnum)
        {
            DocumentationDetail(
                "Value",
                string.IsNullOrWhiteSpace(entry?.Value)
                    ? $"CLR type {FriendlyTypeName(field.FieldType)}."
                    : entry.Value,
                indent);
        }
        if (member is MethodInfo methodInfo && methodInfo.ReturnType != typeof(void))
        {
            DocumentationDetail(
                "Returns",
                string.IsNullOrWhiteSpace(entry?.Returns)
                    ? $"CLR type {FriendlyTypeName(methodInfo.ReturnType)}."
                    : entry.Returns,
                indent);
        }
        if (entry is not null)
        {
            foreach (var exception in entry.Exceptions)
            {
                DocumentationDetail($"May return {exception.Key}", exception.Value, indent);
            }
            if (!string.IsNullOrWhiteSpace(entry.Example))
            {
                DocumentationDetail("Example", entry.Example, indent);
            }
        }
        if (member?.GetCustomAttribute<ObsoleteAttribute>() is { } obsolete)
        {
            var message = string.IsNullOrWhiteSpace(obsolete.Message) ? "This API is obsolete." : obsolete.Message;
            if (!summary.Contains(message, StringComparison.OrdinalIgnoreCase) &&
                !(entry?.Remarks.Contains(message, StringComparison.OrdinalIgnoreCase) ?? false))
            {
                DocumentationDetail("Deprecated", message, indent);
            }
        }
        var link = learnLink ?? (member is null ? null : LearnLink(member));
        if (link is not null)
        {
            DocumentationDetail("Microsoft Learn", link, indent);
        }
    }

    private void DocumentationDetail(string label, string text, string indent)
    {
        Line($"{indent}//");
        Line($"{indent}// {label}:");
        Comment(text, indent);
    }

    private void Comment(string text, string indent)
    {
        var words = Regex.Split(text.Trim(), @"\s+").Where(word => word.Length > 0).ToArray();
        var line = new StringBuilder();
        foreach (var word in words)
        {
            if (line.Length > 0 && line.Length + word.Length + 1 > 108)
            {
                Line($"{indent}// {line}");
                line.Clear();
            }
            if (line.Length > 0) line.Append(' ');
            line.Append(word);
        }
        if (line.Length > 0) Line($"{indent}// {line}");
    }

    private static string LearnLink(MemberInfo member)
    {
        var type = member as Type ?? member.DeclaringType;
        if (type?.FullName is null) return "https://learn.microsoft.com/dotnet/api/microsoft.analysisservices.tabular";
        if (type.IsConstructedGenericType) type = type.GetGenericTypeDefinition();
        var path = (type.FullName ?? type.Name).Replace('+', '.').Replace('`', '-').ToLowerInvariant();
        if (member is not Type && member is not FieldInfo { DeclaringType.IsEnum: true })
        {
            var memberName = member is ConstructorInfo ? "-ctor" : member.Name.ToLowerInvariant();
            path += "." + memberName;
        }
        var view = type.Namespace?.StartsWith("Microsoft.AnalysisServices", StringComparison.Ordinal) == true
            ? "?view=analysisservices-dotnet"
            : string.Empty;
        return $"https://learn.microsoft.com/dotnet/api/{path}{view}";
    }

    private static string ParameterName(ParameterInfo parameter, int index = 0)
    {
        var name = parameter.Name ?? $"argument{index + 1}";
        name = char.ToLowerInvariant(name[0]) + name[1..];
        name = new string(name.Select(character => char.IsLetterOrDigit(character) ? character : '_').ToArray());
        return GoKeywords.Contains(name) || name == "receiver" ? name + "Value" : name;
    }

    private static string Identifier(string value)
    {
        var output = new StringBuilder();
        var uppercase = true;
        foreach (var character in value)
        {
            if (!char.IsLetterOrDigit(character))
            {
                uppercase = true;
                continue;
            }
            output.Append(uppercase ? char.ToUpperInvariant(character) : character);
            uppercase = false;
        }
        if (output.Length == 0 || char.IsDigit(output[0])) output.Insert(0, "Tom");
        return output.ToString();
    }

    private static string FriendlyTypeName(Type type)
    {
        if (type.IsByRef) return FriendlyTypeName(type.GetElementType()!) + "&";
        if (type.IsArray) return FriendlyTypeName(type.GetElementType()!) + "[]";
        if (!type.IsGenericType) return type.FullName ?? type.Name;
        var name = type.GetGenericTypeDefinition().FullName!.Split('`')[0];
        return $"{name}<{string.Join(",", type.GetGenericArguments().Select(FriendlyTypeName))}>";
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    private static string Comma(string value) => string.IsNullOrEmpty(value) ? string.Empty : ", " + value;

    private void Line(string value = "") => _output.AppendLine(value);

    private sealed record ReturnMapping(string GoType, ReturnKind Kind);
    private enum ReturnKind { Primitive, Object, Any }
}

internal sealed class XmlDocumentation
{
    private readonly Dictionary<string, DocumentationEntry> _entries;

    private XmlDocumentation(Dictionary<string, DocumentationEntry> entries)
    {
        _entries = entries;
    }

    public static XmlDocumentation Load(string directory)
    {
        var entries = new Dictionary<string, DocumentationEntry>(StringComparer.Ordinal);
        foreach (var path in Directory.EnumerateFiles(directory, "Microsoft.AnalysisServices*.xml"))
        {
            var document = XDocument.Load(path, LoadOptions.PreserveWhitespace);
            foreach (var member in document.Descendants("member"))
            {
                var name = member.Attribute("name")?.Value;
                if (string.IsNullOrWhiteSpace(name)) continue;
                entries[name] = new DocumentationEntry(
                    Text(member.Element("summary")),
                    Text(member.Element("remarks")),
                    Text(member.Element("returns")),
                    Text(member.Element("value")),
                    Text(member.Element("example")),
                    member.Elements("param")
                        .Where(element => element.Attribute("name") is not null)
                        .ToDictionary(
                            element => element.Attribute("name")!.Value,
                            Text,
                            StringComparer.Ordinal),
                    member.Elements("typeparam")
                        .Where(element => element.Attribute("name") is not null)
                        .ToDictionary(
                            element => element.Attribute("name")!.Value,
                            Text,
                            StringComparer.Ordinal),
                    member.Elements("exception")
                        .ToDictionary(
                            element => DisplayReference(element.Attribute("cref")?.Value),
                            Text,
                            StringComparer.Ordinal));
            }
        }
        return new XmlDocumentation(entries);
    }

    public DocumentationEntry? Find(MemberInfo member)
    {
        member = NormalizeMember(member);
        var id = DocumentationId(member);
        return id is not null && _entries.TryGetValue(id, out var entry) ? entry : null;
    }

    private static MemberInfo NormalizeMember(MemberInfo member)
    {
        var declaringType = member.DeclaringType;
        if (declaringType is null || !declaringType.IsConstructedGenericType) return member;
        var definition = declaringType.GetGenericTypeDefinition();
        try
        {
            return definition.GetMembers(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
                       .FirstOrDefault(candidate => candidate.MetadataToken == member.MetadataToken)
                   ?? member;
        }
        catch (InvalidOperationException)
        {
            return member;
        }
    }

    private static string? DocumentationId(MemberInfo member) => member switch
    {
        Type type => "T:" + TypeName(type),
        ConstructorInfo constructor => "M:" + TypeName(constructor.DeclaringType!) + ".#ctor" +
                                       ParameterList(constructor.GetParameters()),
        MethodInfo method => "M:" + TypeName(method.DeclaringType!) + "." + method.Name +
                             (method.IsGenericMethodDefinition ? "``" + method.GetGenericArguments().Length : "") +
                             ParameterList(method.GetParameters()),
        PropertyInfo property => "P:" + TypeName(property.DeclaringType!) + "." + property.Name +
                                 ParameterList(property.GetIndexParameters()),
        FieldInfo field => "F:" + TypeName(field.DeclaringType!) + "." + field.Name,
        EventInfo eventInfo => "E:" + TypeName(eventInfo.DeclaringType!) + "." + eventInfo.Name,
        _ => null
    };

    private static string ParameterList(ParameterInfo[] parameters) =>
        parameters.Length == 0
            ? string.Empty
            : "(" + string.Join(",", parameters.Select(parameter => ParameterTypeName(parameter.ParameterType))) + ")";

    private static string TypeName(Type type) =>
        (type.FullName ?? type.Name).Replace('+', '.');

    private static string ParameterTypeName(Type type)
    {
        if (type.IsByRef) return ParameterTypeName(type.GetElementType()!) + "@";
        if (type.IsPointer) return ParameterTypeName(type.GetElementType()!) + "*";
        if (type.IsArray)
        {
            var rank = type.GetArrayRank();
            return ParameterTypeName(type.GetElementType()!) +
                   (rank == 1 ? "[]" : "[" + string.Join(",", Enumerable.Repeat("0:", rank)) + "]");
        }
        if (type.IsGenericParameter)
        {
            return type.DeclaringMethod is null ? "`" + type.GenericParameterPosition : "``" + type.GenericParameterPosition;
        }
        if (type.IsGenericType)
        {
            var definitionName = TypeName(type.GetGenericTypeDefinition()).Split('`')[0];
            return definitionName + "{" + string.Join(",", type.GetGenericArguments().Select(ParameterTypeName)) + "}";
        }
        return TypeName(type);
    }

    private static string Text(XElement? element)
    {
        if (element is null) return string.Empty;
        var builder = new StringBuilder();
        AppendNode(element, builder);
        return Regex.Replace(builder.ToString(), @"\s+", " ").Trim();
    }

    private static void AppendNode(XNode node, StringBuilder builder)
    {
        if (node is XText text)
        {
            builder.Append(text.Value);
            return;
        }
        if (node is not XElement element) return;
        switch (element.Name.LocalName)
        {
            case "see":
                builder.Append(element.Attribute("langword")?.Value
                               ?? element.Attribute("href")?.Value
                               ?? DisplayReference(element.Attribute("cref")?.Value));
                return;
            case "paramref":
            case "typeparamref":
                builder.Append(element.Attribute("name")?.Value);
                return;
            case "c":
            case "code":
                builder.Append('`').Append(element.Value.Trim()).Append('`');
                return;
        }
        foreach (var child in element.Nodes())
        {
            AppendNode(child, builder);
        }
        if (element.Name.LocalName is "para" or "item" or "term" or "description")
        {
            builder.Append(' ');
        }
    }

    private static string DisplayReference(string? reference)
    {
        if (string.IsNullOrWhiteSpace(reference)) return string.Empty;
        var value = reference.Length > 2 && reference[1] == ':' ? reference[2..] : reference;
        return value.Replace('#', '.');
    }
}

internal sealed record DocumentationEntry(
    string Summary,
    string Remarks,
    string Returns,
    string Value,
    string Example,
    IReadOnlyDictionary<string, string> Parameters,
    IReadOnlyDictionary<string, string> TypeParameters,
    IReadOnlyDictionary<string, string> Exceptions);
