using System.Reflection;
using System.Text;
using TOM = Microsoft.AnalysisServices.Tabular;

var outputPath = args.Length > 0
    ? Path.GetFullPath(args[0])
    : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "generated.go"));

var generator = new GoGenerator(typeof(TOM.Server).Assembly);
Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generator.Generate(), new UTF8Encoding(false));
Console.WriteLine($"Generated {outputPath}: {generator.GeneratedTypeCount} types, {generator.GeneratedMemberCount} members");

internal sealed class GoGenerator
{
    private static readonly HashSet<string> GoKeywords =
    [
        "break", "default", "func", "interface", "select", "case", "defer", "go", "map",
        "struct", "chan", "else", "goto", "package", "switch", "const", "fallthrough",
        "if", "range", "type", "continue", "for", "import", "return", "var"
    ];

    private readonly Assembly _assembly;
    private readonly Type[] _types;
    private readonly Dictionary<Type, string> _goNames = [];
    private readonly StringBuilder _output = new();

    public GoGenerator(Assembly assembly)
    {
        _assembly = assembly;
        _types = assembly.GetExportedTypes()
            .Where(type => type.Namespace?.StartsWith("Microsoft.AnalysisServices.Tabular", StringComparison.Ordinal) == true)
            .OrderBy(type => type.FullName, StringComparer.Ordinal)
            .ToArray();
        BuildTypeNames();
    }

    public int GeneratedTypeCount { get; private set; }
    public int GeneratedMemberCount { get; private set; }

    public string Generate()
    {
        Line("//go:build windows");
        Line();
        Line("// Code generated by TomGen from Microsoft.AnalysisServices; DO NOT EDIT.");
        Line();
        Line("package tom");
        Line();

        foreach (var type in _types.Where(CanGenerateType))
        {
            if (type.IsEnum)
            {
                GenerateEnum(type);
            }
            else
            {
                GenerateObject(type);
            }
            GeneratedTypeCount++;
        }

        var skipped = _types.Where(type => !CanGenerateType(type)).Select(type => type.FullName).ToArray();
        if (skipped.Length > 0)
        {
            Line("// Open generic CLR types remain available through Client.Call and Value.InvokeAny:");
            foreach (var name in skipped)
            {
                Line($"//   {name}");
            }
        }

        return _output.ToString();
    }

    private void GenerateEnum(Type type)
    {
        var goName = _goNames[type];
        Line($"// {goName} maps CLR enum {type.FullName}.");
        Line($"type {goName} string");
        Line();
        Line("const (");
        foreach (var name in Enum.GetNames(type))
        {
            Line($"\t{goName}{Identifier(name)} {goName} = {Quote(name)}");
        }
        Line(")");
        Line();
    }

    private void GenerateObject(Type type)
    {
        var goName = _goNames[type];
        var clrName = FriendlyTypeName(type);
        Line($"// {goName} maps CLR type {clrName}.");
        Line($"type {goName} struct {{ objectRef }}");
        Line();
        Line($"func As{goName}(value Value) {goName} {{ return {goName}{{objectRef: objectRef{{Value: value}}}} }}");
        Line();

        if (type is { IsClass: true, IsAbstract: false })
        {
            GenerateConstructors(type, goName, clrName);
        }

        var reservedInstanceNames = type.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(method => !method.IsSpecialName)
            .Select(method => Identifier(method.Name))
            .ToHashSet(StringComparer.Ordinal);

        foreach (var property in type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
                     .Where(property => property.GetIndexParameters().Length == 0)
                     .GroupBy(property => property.Name, StringComparer.Ordinal)
                     .Select(group => group.First())
                     .OrderBy(property => property.Name, StringComparer.Ordinal))
        {
            GenerateInstanceProperty(goName, property, reservedInstanceNames);
        }

        foreach (var field in type.GetFields(BindingFlags.Instance | BindingFlags.Public)
                     .OrderBy(field => field.Name, StringComparer.Ordinal))
        {
            GenerateInstanceField(goName, field, reservedInstanceNames);
        }

        GenerateInstanceMethods(type, goName);
        GenerateStaticProperties(type, goName, clrName);
        GenerateStaticFields(type, goName, clrName);
        GenerateStaticMethods(type, goName, clrName);
    }

    private void GenerateConstructors(Type type, string goName, string clrName)
    {
        var constructors = type.GetConstructors(BindingFlags.Instance | BindingFlags.Public)
            .OrderBy(constructor => constructor.GetParameters().Length)
            .ThenBy(SignatureKey, StringComparer.Ordinal)
            .ToArray();
        var names = OverloadNames("New" + goName, constructors);
        for (var index = 0; index < constructors.Length; index++)
        {
            var constructor = constructors[index];
            var parameters = constructor.GetParameters();
            var declaration = ParameterDeclaration(parameters);
            Line($"func {names[index]}(client *Client{Comma(declaration)}) ({goName}, error) {{");
            Line($"\tvalue, err := client.CreateExact({Quote(clrName)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})");
            Line($"\treturn As{goName}(value), err");
            Line("}");
            Line();
            GeneratedMemberCount++;
        }
    }

    private void GenerateInstanceProperty(string owner, PropertyInfo property, HashSet<string> reservedNames)
    {
        var propertyName = Identifier(property.Name);
        var getterName = reservedNames.Contains(propertyName) ? "Get" + propertyName : propertyName;
        if (property.CanRead && property.GetMethod is { IsStatic: false })
        {
            GenerateReadBody($"func (receiver {owner}) {getterName}()", property.PropertyType,
                $"receiver.objectRef.Value.Get({Quote(property.Name)}, &result)",
                $"receiver.objectRef.Value.GetValue({Quote(property.Name)})",
                $"receiver.objectRef.Value.GetAny({Quote(property.Name)})");
            GeneratedMemberCount++;
        }
        if (property.CanWrite && property.SetMethod is { IsStatic: false })
        {
            var parameterType = GoParameterType(property.PropertyType);
            Line($"func (receiver {owner}) Set{propertyName}(input {parameterType}) error {{");
            Line($"\treturn receiver.objectRef.Value.Set({Quote(property.Name)}, input)");
            Line("}");
            Line();
            GeneratedMemberCount++;
        }
    }

    private void GenerateInstanceField(string owner, FieldInfo field, HashSet<string> reservedNames)
    {
        var fieldName = Identifier(field.Name);
        var getterName = reservedNames.Contains(fieldName) ? "Get" + fieldName : fieldName;
        GenerateReadBody($"func (receiver {owner}) {getterName}()", field.FieldType,
            $"receiver.objectRef.Value.GetField({Quote(field.Name)}, &result)",
            $"receiver.objectRef.Value.GetFieldValue({Quote(field.Name)})",
            $"receiver.objectRef.Value.GetFieldAny({Quote(field.Name)})");
        GeneratedMemberCount++;
        if (!field.IsInitOnly && !field.IsLiteral)
        {
            Line($"func (receiver {owner}) Set{fieldName}(input {GoParameterType(field.FieldType)}) error {{");
            Line($"\treturn receiver.objectRef.Value.SetField({Quote(field.Name)}, input)");
            Line("}");
            Line();
            GeneratedMemberCount++;
        }
    }

    private void GenerateInstanceMethods(Type type, string owner)
    {
        var groups = type.GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(method => !method.IsSpecialName && method.DeclaringType != typeof(object))
            .GroupBy(method => method.Name, StringComparer.Ordinal)
            .OrderBy(group => group.Key, StringComparer.Ordinal);

        foreach (var group in groups)
        {
            var methods = group.OrderBy(method => method.GetParameters().Length)
                .ThenBy(SignatureKey, StringComparer.Ordinal)
                .ToArray();
            var names = OverloadNames(Identifier(group.Key), methods);
            for (var index = 0; index < methods.Length; index++)
            {
                GenerateInstanceMethod(owner, names[index], methods[index]);
            }
        }
    }

    private void GenerateInstanceMethod(string owner, string name, MethodInfo method)
    {
        var parameters = method.GetParameters();
        if (method.IsGenericMethodDefinition || parameters.Any(parameter => parameter.ParameterType.IsByRef))
        {
            Line($"func (receiver {owner}) {name}(args ...any) (any, error) {{");
            Line($"\treturn receiver.objectRef.Value.InvokeAny({Quote(method.Name)}, args...)");
            Line("}");
            Line();
            GeneratedMemberCount++;
            return;
        }

        var declaration = ParameterDeclaration(parameters);
        GenerateInvokeBody(
            $"func (receiver {owner}) {name}({declaration})",
            method.ReturnType,
            $"receiver.objectRef.Value.InvokeExact({Quote(method.Name)}, {TypeList(parameters)}, &result{Comma(ArgumentList(parameters))})",
            $"receiver.objectRef.Value.InvokeExactValue({Quote(method.Name)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})",
            $"receiver.objectRef.Value.InvokeExactAny({Quote(method.Name)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})",
            $"receiver.objectRef.Value.InvokeExact({Quote(method.Name)}, {TypeList(parameters)}, nil{Comma(ArgumentList(parameters))})");
        GeneratedMemberCount++;
    }

    private void GenerateStaticProperties(Type type, string owner, string clrName)
    {
        foreach (var property in type.GetProperties(BindingFlags.Static | BindingFlags.Public)
                     .Where(property => property.GetIndexParameters().Length == 0)
                     .GroupBy(property => property.Name, StringComparer.Ordinal)
                     .Select(group => group.First())
                     .OrderBy(property => property.Name, StringComparer.Ordinal))
        {
            var name = Identifier(property.Name);
            if (property.CanRead)
            {
                GenerateReadBody($"func {owner}{name}(client *Client)", property.PropertyType,
                    $"client.GetStatic({Quote(clrName)}, {Quote(property.Name)}, &result)",
                    $"client.GetStaticValue({Quote(clrName)}, {Quote(property.Name)})",
                    $"client.GetStaticAny({Quote(clrName)}, {Quote(property.Name)})");
                GeneratedMemberCount++;
            }
            if (property.CanWrite)
            {
                Line($"func Set{owner}{name}(client *Client, input {GoParameterType(property.PropertyType)}) error {{");
                Line($"\treturn client.SetStatic({Quote(clrName)}, {Quote(property.Name)}, input)");
                Line("}");
                Line();
                GeneratedMemberCount++;
            }
        }
    }

    private void GenerateStaticFields(Type type, string owner, string clrName)
    {
        foreach (var field in type.GetFields(BindingFlags.Static | BindingFlags.Public)
                     .OrderBy(field => field.Name, StringComparer.Ordinal))
        {
            var name = Identifier(field.Name);
            GenerateReadBody($"func {owner}{name}(client *Client)", field.FieldType,
                $"client.GetStaticField({Quote(clrName)}, {Quote(field.Name)}, &result)",
                $"client.GetStaticFieldValue({Quote(clrName)}, {Quote(field.Name)})",
                $"client.GetStaticFieldAny({Quote(clrName)}, {Quote(field.Name)})");
            GeneratedMemberCount++;
            if (!field.IsInitOnly && !field.IsLiteral)
            {
                Line($"func Set{owner}{name}(client *Client, input {GoParameterType(field.FieldType)}) error {{");
                Line($"\treturn client.SetStaticField({Quote(clrName)}, {Quote(field.Name)}, input)");
                Line("}");
                Line();
                GeneratedMemberCount++;
            }
        }
    }

    private void GenerateStaticMethods(Type type, string owner, string clrName)
    {
        var groups = type.GetMethods(BindingFlags.Static | BindingFlags.Public)
            .Where(method => !method.IsSpecialName)
            .GroupBy(method => method.Name, StringComparer.Ordinal)
            .OrderBy(group => group.Key, StringComparer.Ordinal);
        foreach (var group in groups)
        {
            var methods = group.OrderBy(method => method.GetParameters().Length)
                .ThenBy(SignatureKey, StringComparer.Ordinal)
                .ToArray();
            var names = OverloadNames(owner + Identifier(group.Key), methods);
            for (var index = 0; index < methods.Length; index++)
            {
                var method = methods[index];
                var parameters = method.GetParameters();
                if (method.IsGenericMethodDefinition || parameters.Any(parameter => parameter.ParameterType.IsByRef))
                {
                    Line($"func {names[index]}(client *Client, args ...any) (any, error) {{");
                    Line($"\treturn client.InvokeStaticAny({Quote(clrName)}, {Quote(method.Name)}, args...)");
                    Line("}");
                    Line();
                    GeneratedMemberCount++;
                    continue;
                }

                GenerateInvokeBody(
                    $"func {names[index]}(client *Client{Comma(ParameterDeclaration(parameters))})",
                    method.ReturnType,
                    $"client.InvokeStaticExact({Quote(clrName)}, {Quote(method.Name)}, {TypeList(parameters)}, &result{Comma(ArgumentList(parameters))})",
                    $"client.InvokeStaticExactValue({Quote(clrName)}, {Quote(method.Name)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})",
                    $"client.InvokeStaticExactAny({Quote(clrName)}, {Quote(method.Name)}, {TypeList(parameters)}{Comma(ArgumentList(parameters))})",
                    $"client.InvokeStaticExact({Quote(clrName)}, {Quote(method.Name)}, {TypeList(parameters)}, nil{Comma(ArgumentList(parameters))})");
                GeneratedMemberCount++;
            }
        }
    }

    private void GenerateReadBody(string declaration, Type resultType, string primitiveCall, string objectCall, string anyCall)
    {
        var mapping = MapReturnType(resultType);
        Line($"{declaration} ({mapping.GoType}, error) {{");
        if (mapping.Kind == ReturnKind.Object)
        {
            Line($"\tresult, err := {objectCall}");
            Line($"\treturn As{mapping.GoType}(result), err");
        }
        else if (mapping.Kind == ReturnKind.Any)
        {
            Line($"\treturn {anyCall}");
        }
        else
        {
            Line($"\tvar result {mapping.GoType}");
            Line($"\terr := {primitiveCall}");
            Line("\treturn result, err");
        }
        Line("}");
        Line();
    }

    private void GenerateInvokeBody(
        string declaration,
        Type resultType,
        string primitiveCall,
        string objectCall,
        string anyCall,
        string voidCall)
    {
        if (resultType == typeof(void))
        {
            Line($"{declaration} error {{");
            Line($"\treturn {voidCall}");
            Line("}");
            Line();
            return;
        }

        var mapping = MapReturnType(resultType);
        Line($"{declaration} ({mapping.GoType}, error) {{");
        if (mapping.Kind == ReturnKind.Object)
        {
            Line($"\tresult, err := {objectCall}");
            Line($"\treturn As{mapping.GoType}(result), err");
        }
        else if (mapping.Kind == ReturnKind.Any)
        {
            Line($"\treturn {anyCall}");
        }
        else
        {
            Line($"\tvar result {mapping.GoType}");
            Line($"\terr := {primitiveCall}");
            Line("\treturn result, err");
        }
        Line("}");
        Line();
    }

    private ReturnMapping MapReturnType(Type type)
    {
        var nullable = Nullable.GetUnderlyingType(type);
        type = nullable ?? type;
        if (_goNames.TryGetValue(type, out var goName))
        {
            return type.IsEnum
                ? new ReturnMapping(goName, ReturnKind.Primitive)
                : new ReturnMapping(goName, ReturnKind.Object);
        }
        return type switch
        {
            _ when type == typeof(string) => new("string", ReturnKind.Primitive),
            _ when type == typeof(bool) => new("bool", ReturnKind.Primitive),
            _ when type == typeof(byte) => new("uint8", ReturnKind.Primitive),
            _ when type == typeof(sbyte) => new("int8", ReturnKind.Primitive),
            _ when type == typeof(short) => new("int16", ReturnKind.Primitive),
            _ when type == typeof(ushort) => new("uint16", ReturnKind.Primitive),
            _ when type == typeof(int) => new("int", ReturnKind.Primitive),
            _ when type == typeof(uint) => new("uint", ReturnKind.Primitive),
            _ when type == typeof(long) => new("int64", ReturnKind.Primitive),
            _ when type == typeof(ulong) => new("uint64", ReturnKind.Primitive),
            _ when type == typeof(float) => new("float32", ReturnKind.Primitive),
            _ when type == typeof(double) || type == typeof(decimal) => new("float64", ReturnKind.Primitive),
            _ when type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(TimeSpan)
                => new("string", ReturnKind.Primitive),
            _ => new("any", ReturnKind.Any)
        };
    }

    private string GoParameterType(Type type)
    {
        if (type.IsByRef) type = type.GetElementType()!;
        var nullable = Nullable.GetUnderlyingType(type);
        type = nullable ?? type;
        string result;
        if (_goNames.TryGetValue(type, out var goName))
        {
            result = goName;
        }
        else
        {
            result = MapReturnType(type).GoType;
        }
        return nullable is not null && result != "any" ? "*" + result : result;
    }

    private string ParameterDeclaration(ParameterInfo[] parameters) =>
        string.Join(", ", parameters.Select((parameter, index) =>
            $"{ParameterName(parameter, index)} {GoParameterType(parameter.ParameterType)}"));

    private string ArgumentList(ParameterInfo[] parameters) =>
        string.Join(", ", parameters.Select(ParameterName));

    private string TypeList(ParameterInfo[] parameters) =>
        "[]string{" + string.Join(", ", parameters.Select(parameter => Quote(FriendlyTypeName(parameter.ParameterType)))) + "}";

    private static string SignatureKey(MethodBase method) =>
        string.Join("|", method.GetParameters().Select(parameter => FriendlyTypeName(parameter.ParameterType)));

    private string[] OverloadNames(string baseName, MethodBase[] methods)
    {
        if (methods.Length == 1) return [baseName];
        var result = new string[methods.Length];
        var used = new HashSet<string>(StringComparer.Ordinal);
        for (var index = 0; index < methods.Length; index++)
        {
            var candidate = index == 0 ? baseName : baseName + "With" + ParameterSuffix(methods[index].GetParameters());
            if (!used.Add(candidate))
            {
                var suffix = 2;
                while (!used.Add(candidate + suffix)) suffix++;
                candidate += suffix;
            }
            result[index] = candidate;
        }
        return result;
    }

    private string ParameterSuffix(ParameterInfo[] parameters)
    {
        if (parameters.Length == 0) return "NoArguments";
        var names = parameters.Select((parameter, index) =>
        {
            var name = Identifier(parameter.Name ?? $"Argument{index + 1}");
            return name.Length > 1 ? name : TypeIdentifier(parameter.ParameterType);
        });
        return string.Concat(names);
    }

    private string TypeIdentifier(Type type)
    {
        if (type.IsByRef) type = type.GetElementType()!;
        if (type.IsArray) return TypeIdentifier(type.GetElementType()!) + "Array";
        return _goNames.TryGetValue(type, out var name) ? name : Identifier(type.Name.Split('`')[0]);
    }

    private void BuildTypeNames()
    {
        var used = new HashSet<string>(StringComparer.Ordinal)
        {
            "Client", "Value", "Instance"
        };
        foreach (var type in _types.Where(CanGenerateType))
        {
            var baseName = Identifier(type.Name.Split('`')[0].Replace('+', '_'));
            var name = baseName;
            for (var suffix = 2; !used.Add(name); suffix++)
            {
                name = baseName + suffix;
            }
            _goNames[type] = name;
        }
    }

    private static bool CanGenerateType(Type type) => !type.ContainsGenericParameters;

    private static string ParameterName(ParameterInfo parameter, int index = 0)
    {
        var name = parameter.Name ?? $"argument{index + 1}";
        name = char.ToLowerInvariant(name[0]) + name[1..];
        name = new string(name.Select(character => char.IsLetterOrDigit(character) ? character : '_').ToArray());
        return GoKeywords.Contains(name) || name == "receiver" ? name + "Value" : name;
    }

    private static string Identifier(string value)
    {
        var output = new StringBuilder();
        var uppercase = true;
        foreach (var character in value)
        {
            if (!char.IsLetterOrDigit(character))
            {
                uppercase = true;
                continue;
            }
            output.Append(uppercase ? char.ToUpperInvariant(character) : character);
            uppercase = false;
        }
        if (output.Length == 0 || char.IsDigit(output[0])) output.Insert(0, "Tom");
        return output.ToString();
    }

    private static string FriendlyTypeName(Type type)
    {
        if (type.IsByRef) return FriendlyTypeName(type.GetElementType()!) + "&";
        if (type.IsArray) return FriendlyTypeName(type.GetElementType()!) + "[]";
        if (!type.IsGenericType) return type.FullName ?? type.Name;
        var name = type.GetGenericTypeDefinition().FullName!.Split('`')[0];
        return $"{name}<{string.Join(",", type.GetGenericArguments().Select(FriendlyTypeName))}>";
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    private static string Comma(string value) => string.IsNullOrEmpty(value) ? string.Empty : ", " + value;

    private void Line(string value = "") => _output.AppendLine(value);

    private sealed record ReturnMapping(string GoType, ReturnKind Kind);
    private enum ReturnKind { Primitive, Object, Any }
}
