<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <InvariantGlobalization>false</InvariantGlobalization>
    <IlcGenerateCompleteTypeMetadata>true</IlcGenerateCompleteTypeMetadata>
    <IlcGenerateStackTraceData>true</IlcGenerateStackTraceData>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>tombridge</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AnalysisServices" Version="19.117.0" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.AnalysisServices.Core" />
    <TrimmerRootAssembly Include="Microsoft.AnalysisServices.Tabular" />
    <TrimmerRootAssembly Include="System.Private.Xml" />
    <TrimmerRootAssembly Include="System.Xml.ReaderWriter" />
    <RdXmlFile Include="rd.xml" />
  </ItemGroup>
</Project>
